# Generated by Django 3.1.3 on 2020-11-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
                ('destinataire', models.CharField(max_length=120)),
                ('produits', models.TextField(blank=True, null=True)),
                ('volume', models.CharField(max_length=120)),
                ('packaging', models.TextField(blank=True, null=True)),
                ('origine', models.CharField(max_length=120)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('devise', models.CharField(max_length=50)),
                ('incoterm', models.CharField(max_length=50)),
                ('embarquement', models.DateField()),
                ('moyen_de_paiement', models.CharField(max_length=50)),
                ('reference_contrepartie', models.TextField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
