# Generated by Django 3.1.3 on 2020-11-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='documents/covers/'),
        ),
    ]
