# Generated by Django 3.1.3 on 2020-11-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0004_auto_20201120_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/pdfs/'),
        ),
    ]
