# Generated by Django 3.1.3 on 2020-12-01 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0005_auto_20201120_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='affaires',
            name='reference_contart',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affaires',
            name='statut',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SuiviDHL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_dhl', models.IntegerField()),
                ('date_arrive', models.DateField()),
                ('affaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='affaires.affaires')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviConteneur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bl', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=120)),
                ('moves', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('vessel', models.CharField(max_length=120)),
                ('affaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='affaires.affaires')),
            ],
        ),
    ]
