# Generated by Django 3.1.3 on 2020-12-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0006_auto_20201201_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviPaiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_bl', models.DateField()),
                ('date_arrivee', models.DateField()),
                ('echeance_paiement', models.DateField()),
                ('date_valeur', models.DateField()),
                ('date_reception', models.DateField()),
                ('date_bl_a_vue', models.DateField()),
                ('date_arrivee_a_vue', models.DateField()),
                ('echeance_paiement_a_vue', models.DateField()),
                ('date_valeur_a_vue', models.DateField()),
                ('date_reception_a_vue', models.DateField()),
                ('affaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='affaires.affaires')),
            ],
        ),
    ]
